on: [push, pull_request]

name: Continuous Integration

jobs:
    test:
        name: Tests (Symfony ${{ matrix.symfony-version }} & PHP ${{ matrix.php-version }})
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['7.3', '7.4']
                symfony-version: ['3.4', '4.4', '5.1']

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                 php-version: ${{ matrix.php-version }}
                 extensions: mbstring, json, xml
                 coverage: pcov

            - name: Detect dependency cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                 path: ${{ steps.composer-cache.outputs.dir }}
                 key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                 restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Switch Symfony components to version ${{ matrix.symfony-version }}
              run: composer remove friendsofphp/php-cs-fixer --dev && composer require "symfony/symfony:${{ matrix.symfony-version }}.*" --no-update && composer update symfony/* --prefer-dist --no-progress --no-suggest

            - name: Run PHPUnit
              run: ./vendor/bin/phpunit

    code-style:
        name: Code standards
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: none

            - name: Detect dependency cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                 path: ${{ steps.composer-cache.outputs.dir }}
                 key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                 restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Check code standards
              run: ./vendor/bin/php-cs-fixer fix --dry-run -v
