on: [push, pull_request]

name: Continuous Integration

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                 php-version: '7.4'
                 extensions: mbstring, json, xml
                 coverage: pcov

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: Run PHPUnit
              run: ./vendor/bin/phpunit
